[versions]
# Core
paper-api = "1.21.10-R0.1-SNAPSHOT"
velocity-api = "3.4.0-SNAPSHOT"
#javax-annotation = "1.3.2"

# Crescent Sun API versions
crescent-core-api = "2.0.6"
crescent-common = "1.0.6"
artifacts-api = "1.0.22"
crystals-api = "1.0.10"
triumphcmd = "1.0.0"

# Other dependencies
hikari-cp = "7.0.2"
protoweaver = "1.4.9"
crescentmsg = "1.2.1"

# Test
junit_version = "5.11.0"
mockbukkit_version = "3.107.0"

[libraries]
# Paper
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api"}
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari-cp"}
protoweaver-paper = { module = "me.mrnavastar.protoweaver:paper", version.ref = "protoweaver"}
#javax-annotation = {module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation"}
crescentmsg = { module = "it.crescentsun:crescentmsg", version.ref = "crescentmsg"}

# Velocity
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity-api"}
protoweaver-velocity = { module = "me.mrnavastar.protoweaver:proxy", version.ref = "protoweaver"}

# Crescent Sun API reps
crescent-core-api = { module = "it.crescentsun.api:crescent-core", version.ref = "crescent-core-api"}
crescent-common = { module = "it.crescentsun.api:crescent-common", version.ref = "crescent-common"}
triumphcmd = { module = "it.crescentsun:triumph-cmd", version.ref = "triumphcmd"}
artifacts-api = { module = "it.crescentsun.api:artifacts", version.ref = "artifacts-api"}
crystals-api = { module = "it.crescentsun.api:crystals", version.ref = "crystals-api"}

# Test

junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit_version"}
mockbukkit = { module = "com.github.seeseemelk:MockBukkit-v1.21", version.ref = "mockbukkit_version"}

[plugins]
java-library = { id = "java-library"}
maven-publish = {id = "maven-publish"}
shadow = {id = "io.github.goooler.shadow", version = "8.1.8"}